# Project information
site_name: 'PatCit'
site_description: 'Making Patent Citations Uncool Again'
site_author: 'Cyril Verluise & Gaétan de Rassenfosse'
#site_url: 'https://cverluise.github.io/PatCit/'

# Repository
repo_name: 'cverluise/PatCit'
repo_url: 'https://github.com/cverluise/PatCit'

# Copyright
copyright: 'Copyright; 2019 Gaétan de Rassenfosse and Cyril Verluise'

# Configuration
theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'

# Customization
extra:
  manifest: 'manifest.webmanifest'
  social:
    - type: 'github'
      link: 'https://github.com/cverluise'
    - type: 'twitter'
      link: 'https://twitter.com/cyrilverluise'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/cyril-verluise-80184347/'

# Google Analytics
google_analytics:
  - 'UA-156947083-2'
  - 'auto'

# Extensions
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
  - pymdownx.details:
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'


# Page tree

nav:
  - About:
    - Project: index.md
    - Roadmap: roadmap.md
    - Team: team.md
  - Keep me updated: update.md
  - Data:
    - Download: download.md
    - Explore: explore.md
    - Versions: versions.md
  - Contribute:
    - Contributions: contributing.md
    - Code of Conduct: code-of-conduct.md
  - How it works:
     - Extract, Parse, Consolidate: extract-parse-consolidate.md
     - Classify: classify.md
  - Awesome resources: awesome.md
  - Vocabulary: vocabulary.md
  - License:
    - MIT2: license-mit.md
    - CC4: license-cc.md
